add_vhdl_file sources_1 MSGPACK ../../../msgpack-vhdl/src/msgpack/object/msgpack_object.vhd
add_vhdl_file sources_1 MSGPACK ../../../msgpack-vhdl/src/msgpack/pipework/pipework_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../msgpack-vhdl/src/msgpack/pipework/reducer.vhd
add_vhdl_file sources_1 MSGPACK ../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_reducer.vhd
add_vhdl_file sources_1 MSGPACK ../../../msgpack-vhdl/src/msgpack/object/msgpack_object_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../msgpack-vhdl/src/msgpack/object/msgpack_object_packer.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_types.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_models.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_master_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_slave_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sim_1     WORK ../../../src/msgpack_object_packer/vhdl/test_bench.vhd
